// Barrel file for presentational components, which will be used to compose our smart containers;
export { default as AllCampusesView } from "./AllCampusesView";
export { default as CampusView } from "./CampusView";
export { default as AllStudentsView } from "./AllStudentView";
export { default as StudentView } from "./StudentView";
export { default as AddCampusFormView } from "./AddCampusFormView";
export { default as EditCampusFormView } from "./EditCampusFormView";
export { default as AddStudentFormView } from "./AddStudentFormView";
export { default as EditStudentFormView } from "./EditStudentFormView";
export { default as ComboBoxView } from "./ComboBoxView";
export { default as StudentCardView } from "./StudentCardView";
export { default as StudentRowView } from "./StudentRowView";
export { default as CampusCardView } from "./CampusCardView";
